### ISSUE TITLE
slides are skipped without processing

### ISSUE THREAD

**Issue by sbalci** [MaryamHaghighat/PathProfiler#3]
Hi, I wanted to try the workflow with our digital slides.
When I use the code the slides are skipped without processing. Is there a known reason for that?
Best wishes
Serdar Balci, MD, Pathologist

```py
PathProfiler % python tissue-segmentation/run.py --save_folder 'tissue-masks/svss' --slide_dir 'svss' --mask_magnification 2.5 --model 'checkpoint_ts.pth'

=> loading checkpoint 'checkpoint_ts.pth'
=> loaded checkpoint 'checkpoint_ts.pth' (epoch 2506)
Processing svss/ANONQRCM4H13V_1_1.svs
Skipped slide ANONQRCM4H13V_1_1
Processing svss/ANON7DHJ4H1L8_1_1.svs
Skipped slide ANON7DHJ4H1L8_1_1
``

**Comment by MaryamHaghighat** [comment]
If an error is raised in lines 310-313, the processing is skipped. It could be due to missing packages or an issue with reading the file.
I have modified line 314 in "PathProfiler/tissue-segmentation/run.py” to print the cause of the error. You can also remove the "try" and "except" command lines (lines 309 and 314-316) to further investigate the issue.
